"""Write client.js directly - no f-strings, no escaping issues"""

lines = []
a = lines.append

a("/**")
a(" * api/client.js - Fetch wrapper with JWT auth.")
a(" */")
a("")
a("const API_BASE = '/api'")
a("")
a("function getToken() {")
a("  return localStorage.getItem('cane_token')")
a("}")
a("")
a("export function setToken(token) {")
a("  if (token) {")
a("    localStorage.setItem('cane_token', token)")
a("  } else {")
a("    localStorage.removeItem('cane_token')")
a("  }")
a("}")
a("")
a("async function request(path, options = {}) {")
a("  const token = getToken()")
a("  const headers = { ...options.headers }")
a("")
a("  if (token) {")
a("    headers['Authorization'] = `Bearer ${token}`")
a("  }")
a("")
a("  if (!(options.body instanceof FormData) && !headers['Content-Type']) {")
a("    headers['Content-Type'] = 'application/json'")
a("  }")
a("")
a("  const res = await fetch(`${API_BASE}${path}`, { ...options, headers })")
a("")
a("  if (res.status === 401) {")
a("    setToken(null)")
a("    window.location.href = '/login'")
a("    throw new Error('Session expired')")
a("  }")
a("")
a("  if (!res.ok) {")
a("    const data = await res.json().catch(() => ({}))")
a("    throw new Error(data.detail || `Request failed: ${res.status}`)")
a("  }")
a("")
a("  return res.json()")
a("}")
a("")
a("// -- Auth --")
a("export async function login(email, password) {")
a("  const form = new FormData()")
a("  form.append('email', email)")
a("  form.append('password', password)")
a("  return request('/auth/login', { method: 'POST', body: form })")
a("}")
a("")
a("export async function getMe() {")
a("  return request('/auth/me')")
a("}")
a("")
a("// -- Workspaces --")
a("export async function getWorkspaces() {")
a("  return request('/workspaces')")
a("}")
a("")
a("export async function createWorkspace(name, description = '') {")
a("  const form = new FormData()")
a("  form.append('name', name)")
a("  form.append('description', description)")
a("  return request('/workspaces', { method: 'POST', body: form })")
a("}")
a("")
a("export async function renameWorkspace(workspaceId, name, description = '') {")
a("  const form = new FormData()")
a("  form.append('name', name)")
a("  form.append('description', description)")
a("  return request(`/workspaces/${workspaceId}`, { method: 'PUT', body: form })")
a("}")
a("")
a("export async function deleteWorkspace(workspaceId) {")
a("  return request(`/workspaces/${workspaceId}`, { method: 'DELETE' })")
a("}")
a("")
a("// -- Documents --")
a("export async function getDocuments(workspaceId = '') {")
a("  const params = workspaceId ? `?workspace_id=${workspaceId}` : ''")
a("  return request(`/documents${params}`)")
a("}")
a("")
a("export async function uploadDocument(file, workspaceId) {")
a("  const form = new FormData()")
a("  form.append('file', file)")
a("  form.append('workspace_id', workspaceId)")
a("  return request('/documents/upload', { method: 'POST', body: form })")
a("}")
a("")
a("export async function deleteDocument(documentId) {")
a("  return request(`/documents/${documentId}`, { method: 'DELETE' })")
a("}")
a("")
a("// -- Search --")
a("export async function search(query, mode = 'text', n = 10, workspaceId = '') {")
a("  const params = new URLSearchParams({ q: query, mode, n, workspace_id: workspaceId })")
a("  return request(`/search?${params}`)")
a("}")
a("")
a("export async function ask(query, n = 5, workspaceId = '') {")
a("  const params = new URLSearchParams({ q: query, n, workspace_id: workspaceId })")
a("  return request(`/ask?${params}`)")
a("}")
a("")
a("// -- Stats --")
a("export async function getStats() {")
a("  return request('/stats')")
a("}")
a("")
a("// -- Team --")
a("export async function getTeam() {")
a("  return request('/team')")
a("}")
a("")
a("export async function inviteMember(email, name, password, role = 'member') {")
a("  const form = new FormData()")
a("  form.append('email', email)")
a("  form.append('name', name)")
a("  form.append('password', password)")
a("  form.append('role', role)")
a("  return request('/team/invite', { method: 'POST', body: form })")
a("}")
a("")
a("// -- Admin --")
a("export async function adminGetTenants() {")
a("  return request('/admin/tenants')")
a("}")
a("")
a("export async function adminGetTenantDetail(tenantId) {")
a("  return request(`/admin/tenants/${tenantId}`)")
a("}")
a("")
a("export async function adminCreateTenant(data) {")
a("  const form = new FormData()")
a("  Object.entries(data).forEach(([k, v]) => form.append(k, v))")
a("  return request('/admin/tenants', { method: 'POST', body: form })")
a("}")
a("")
a("export async function adminUpdateTenant(tenantId, name, slug = '') {")
a("  const form = new FormData()")
a("  form.append('name', name)")
a("  if (slug) form.append('slug', slug)")
a("  return request(`/admin/tenants/${tenantId}`, { method: 'PUT', body: form })")
a("}")
a("")
a("export async function adminDeleteTenant(tenantId) {")
a("  return request(`/admin/tenants/${tenantId}`, { method: 'DELETE' })")
a("}")
a("")
a("export async function adminUpdateUser(tenantId, userId, email, name = '') {")
a("  const form = new FormData()")
a("  form.append('email', email)")
a("  form.append('name', name)")
a("  return request(`/admin/tenants/${tenantId}/users/${userId}`, { method: 'PUT', body: form })")
a("}")
a("")
a("export async function adminDeleteUser(tenantId, userId) {")
a("  return request(`/admin/tenants/${tenantId}/users/${userId}`, { method: 'DELETE' })")
a("}")
a("")

content = "\n".join(lines)
with open('frontend/src/api/client.js', 'w', encoding='utf-8', newline='\n') as f:
    f.write(content)

# Verify
bt = content.count(chr(96))
paren_bt = content.count("(" + chr(96))
print(f"Written: {bt} backticks, {paren_bt} template calls")
if paren_bt >= 10:
    print("OK")
else:
    print("WARNING")
