"""
osint_models.py -- SQLAlchemy ORM model for OSINT intelligence briefings.

OsintBriefing stores structured intelligence reports generated by the
OSINT agent's scheduled runs. Each briefing contains a severity rating,
extracted entities, source references, and the full analysis content.
"""
import uuid
from datetime import datetime

from sqlalchemy import (
    Column, String, Text, DateTime, Boolean, ForeignKey,
)

from database import Base


def _uuid() -> str:
    return str(uuid.uuid4())


class OsintBriefing(Base):
    __tablename__ = "osint_briefings"

    id = Column(String(36), primary_key=True, default=_uuid)
    workspace_id = Column(String(36), ForeignKey("workspaces.id", ondelete="CASCADE"), nullable=False)
    tenant_id = Column(String(36), ForeignKey("tenants.id"), nullable=False)
    schedule_run_id = Column(String(36), nullable=True)

    title = Column(String(500), default="")
    briefing_type = Column(String(50), default="combined")  # news | threat | social | combined
    severity = Column(String(20), default="info")            # critical | high | medium | low | info
    content = Column(Text, default="")
    sources_json = Column(Text, default="[]")
    entities_json = Column(Text, default="[]")

    alert_sent = Column(Boolean, default=False)
    alert_channel = Column(String(50), nullable=True)

    created_at = Column(DateTime, default=datetime.utcnow)
